### ISSUE TITLE
small changes to donate page

### ISSUE THREAD

**Issue by RouguiFuta** [alecortega/resilientcoders#15]
@muigaiunaka 

**Summary**
Made a couple of changes to the donate link and copy on our website. I created a new branch and made the changes locally but can't push to repo because I don't have access :( LMK what you think
 
**Screenshots** 
<img width="1423" alt="screen shot 2018-11-12 at 11 53 01 am" src="https://user-images.githubusercontent.com/11174351/48362630-118e5180-e672-11e8-8823-11c59b1235eb.png">

<img width="1238" alt="screen shot 2018-11-12 at 11 53 11 am" src="https://user-images.githubusercontent.com/11174351/48362653-1b17b980-e672-11e8-8be1-c47a28c496ac.png">

**URL** 
http://www.resilientcoders.org/get-involved

**New copy**
Check screenshots

**Comment by muigaiunaka** [comment]
Completed by Rougui in PR #21 . Rougui now has access to alec's github to make changes to the website
