### ISSUE TITLE
Update dates: Hackathons, Bootcamp start, Demo Day

### ISSUE THREAD

**Issue by ddelmar** [alecortega/resilientcoders#17]
Hackathons are 11/17, 11/28. Demo Day is 12/13. Bootcamp starts on Jan 21.

**Comment by muigaiunaka** [comment]
@ddelmar not sure where the demo day mention is, what page do you see that on?

**Comment by muigaiunaka** [comment]
All set and pushed live with changes to location of Hackathon and redirect of 50x30 as well on PR #20
